import { Inter } from "next/font/google";
import "./globals.css";

import "./Styles/header.scss"
import "./Styles/form.scss"
import "./Styles/footer.scss"
import "./Styles/hero.scss"
import "./Styles/mobile-menu.scss"
import "./Styles/realization.scss"
import "./Styles/reviews.scss"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hojgrstav",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
